services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    restart: "no"

  db:
    image: mysql:8.0
    container_name: pos_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pos_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
